# Generated by Django 5.0 on 2025-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image2',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image3',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
